PROMPT DROP TABLES
/
PROMPT DROP TABLE "CP_MER"
/
DROP TABLE CP_MER CASCADE CONSTRAINT
/
PROMPT DROP SEQUENCE "cp_mer_seq"
DROP SEQUENCE cp_mer_seq
/
PROMPT DROP TABLE "CP_USERS"
DROP TABLE CP_USERS CASCADE CONSTRAINT
/
PROMPT DROP SEQUENCE "cp_users_seq"
DROP SEQUENCE cp_users_seq
/
PROMPT DROP TABLE "mer_to_usr"
DROP TABLE mer_to_usr CASCADE CONSTRAINT
/
PROMPT DROP SEQUENCE "parent_mer_seq"
DROP SEQUENCE parent_mer_seq
/
PROMPT DROP SEQUENCE "MER_TO_USR_SEQ"
DROP SEQUENCE mer_to_usr_seq
/
PROMPT DROP FUNCTIONS AND PROCEDURES
/
PROMPT DROP FUNCTION "READ_MID_MER"
DROP FUNCTION READ_MID_MER
/
PROMPT DROP FUNCTION "READ_PARENT_MER"
DROP FUNCTION READ_PARENT_MER
/
PROMPT DROP FUNCTION "READ_COUNT_MER"
DROP FUNCTION READ_COUNT_MER
/
PROMPT DROP FUNCTION "READ_END_MER"
DROP FUNCTION READ_END_MER
/
PROMPT DROP FUNCTION "READ_COUNT_CHILD_MER"
DROP FUNCTION READ_COUNT_CHILD_MER
/
PROMPT DROP FUNCTION "READ_COUNT_USR_MER"
DROP FUNCTION READ_COUNT_USR_MER
/
PROMPT DROP FUNCTION "READ_EXISTS_USR_MER"
DROP FUNCTION READ_EXISTS_USR_MER
/
PROMPT DROP FUNCTION "READ_SUM_BROTHERS_MER"
DROP FUNCTION READ_SUM_BROTHERS_MER
/
PROMPT DROP FUNCTION "READ_SUM_CHILD_MER"
DROP FUNCTION READ_SUM_CHILD_MER
/
PROMPT DROP FUNCTION "READ_SUM_PARENT_MER"
DROP FUNCTION READ_SUM_PARENT_MER
/
PROMPT DROP FUNCTION "AVAILABLE_FINANCE"
DROP FUNCTION AVAILABLE_FINANCE
/
PROMPT DROP FUNCTION "CHECK_FINANCE"
DROP FUNCTION CHECK_FINANCE
/
PROMPT DROP FUNCTION "CHECK_DATE_START_FOR_CHILD"
DROP FUNCTION CHECK_DATE_START_FOR_CHILD
/
PROMPT DROP FUNCTION "CHECK_DATE_STOP_FOR_CHILD"
DROP FUNCTION CHECK_DATE_STOP_FOR_CHILD
/
PROMPT DROP FUNCTION "ADD_MER"
DROP FUNCTION ADD_MER
/
PROMPT DROP FUNCTION "DEL_MER"
DROP FUNCTION DEL_MER
/
PROMPT DROP FUNCTION "UPD_FIN_MER"
DROP FUNCTION UPD_FIN_MER
/
PROMPT DROP FUNCTION "ADD_USR_TO_MER"
DROP FUNCTION ADD_USR_TO_MER
/
PROMPT DROP FUNCTION "DEL_USR_IN_MER"
DROP FUNCTION DEL_USR_IN_MER
/
PROMPT DROP FUNCTION "UPD_USR_IN_MER"
DROP FUNCTION UPD_USR_IN_MER
/