PROMPT CREATE TABLE "CP_MER"
CREATE TABLE cp_mer
	(M_ID NUMBER NOT NULL,
	MER_NAME VARCHAR2(120),
	MER_CODE VARCHAR2(120),
	MER_PARENT NUMBER,
	MER_NODE NUMBER,
	CP NUMBER,
	YEAR_START NUMBER(4),
	YEAR_STOP NUMBER(4),
	FIN NUMBER(8,4),
	TYPE_FIN NUMBER(2))
/
PROMPT ADD PK TO TABLE "CP_MER"
ALTER TABLE cp_mer ADD
	(CONSTRAINT cp_mer_pk
	PRIMARY KEY (m_id)
	USING INDEX
	PCTFREE 10)
/
PROMPT CREARE SEQUENCE "cp_mer_seq"
CREATE SEQUENCE cp_mer_seq
	INCREMENT BY 1
	START WITH 1000
	MINVALUE 1
/
PROMPT CREATE TABLE "CP_USERS"
CREATE TABLE cp_users
	(user_id NUMBER NOT NULL,
	user_name VARCHAR2(40))
/
PROMPT ADD PK TO TABLE "CP_USERS"
ALTER TABLE cp_users ADD
	(CONSTRAINT cp_users_pk
	PRIMARY KEY (user_id)
	USING INDEX
	PCTFREE 10)
/
PROMPT CREARE SEQUENCE "cp_users_seq"
CREATE SEQUENCE cp_users_seq
	INCREMENT BY 1
	START WITH 300
	MINVALUE 1
/
PROMPT CREATE TABLE "mer_to_usr"
create table mer_to_usr
	(mtu_id number,
	mer_id number,
	usr_id number)
/
PROMPT ADD PK TO TABLE "mer_to_usr"
ALTER TABLE mer_to_usr ADD
	(CONSTRAINT mer_to_uch_pk
	PRIMARY KEY (mtu_id)
	USING INDEX
	PCTFREE 10)
/
PROMPT CREARE SEQUENCE "parent_mer_seq"
CREATE SEQUENCE parent_mer_seq
	INCREMENT BY 1
	START WITH 2500
	MINVALUE 1
/
PROMPT CREARE SEQUENCE "mer_to_usr_seq"
CREATE SEQUENCE mer_to_usr_seq
	INCREMENT BY 1
	START WITH 700
	MINVALUE 1
/